name: Build and Publish Wine Yolks

on:
  push:
    branches:
      - main
      - brainshead-patch-1
    paths:
      - 'wine/**'
      - '.github/workflows/docker-wine.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Discover Wine yolks
        id: discover_yolks
        run: |
          yolks=$(find ./wine -mindepth 1 -maxdepth 1 -type d -exec basename {} \;)
          echo "Found yolks: $yolks"
          echo "yolk_list=$yolks" >> $GITHUB_OUTPUT

      - name: Build & Push Wine Yolks
        run: |
          for yolk in ${{ steps.discover_yolks.outputs.yolk_list }}; do
            echo "Building $yolk..."
            docker buildx build \
              --platform linux/amd64 \
              --push \
              -t ghcr.io/${{ github.repository_owner }}/yolks:wine_${yolk} \
              -f ./wine/$yolk/Dockerfile \
              ./wine
          done
